### ISSUE TITLE
Change to Panda3d-1.10.8

### ISSUE THREAD

**Issue by lqy0057** [decisionforce/pgdrive#206]
Thanks to panda3d community. The multi-thread render bug is fixed in this new panda version. We will fully test all scripts on all platfroms based on the new panda version before switching the panda3d edition to 1.10.8.
* [x] Windows
* [x] Ubuntu16.04
* [ ] MacOS

**Comment by rdb** [comment]
I also don't recommend putting `panda3d==1.10.5` in your requirements, which prohibits running with newer bugfix releases.

I recommend instead using the tilde-equals operator, such as `panda3d~=1.10.8`, which will allow more recent bugfix releases (such as 1.10.9) but it will still prohibit major release updates (such as 1.11.0).

**Comment by pengzhenghao** [comment]
> I also don't recommend putting `panda3d==1.10.5` in your requirements, which prohibits running with newer bugfix releases.
> 
> I recommend instead using the tilde-equals operator, such as `panda3d~=1.10.8`, which will allow more recent bugfix releases (such as 1.10.9) but it will still prohibit major release updates (such as 1.11.0).
> 
> Minor version updates (1.10.x) of Panda3D are guaranteed to be backward compatible.

Thanks you @rdb so much !!!

We really appreciate your help during the development in previous months! Panda3D is great to our application! We will adopt your suggestion and hope you can continue to help us in the future development! Thanks!

**Comment by lqy0057** [comment]
![Screenshot from 2020-12-30 14-38-44](https://user-images.githubusercontent.com/24489294/103334642-1a8a4900-4aad-11eb-8f82-7e04ce50eff9.png)
Finish check all test scripts and **memory leak** test on ubuntu-16.04

**Comment by lqy0057** [comment]
![Figure_1](https://user-images.githubusercontent.com/24489294/103335415-d3ea1e00-4aaf-11eb-825f-c3637484c484.png)
finish windows tests

**Comment by lqy0057** [comment]
@pengzhenghao please test new panda on mac

**Comment by pengzhenghao** [comment]
<img width="1102" alt="image" src="https://user-images.githubusercontent.com/22206995/103338955-0b11fc80-4abb-11eb-89e2-ff112bdee231.png">


Wait a minute!

Why windows use 200 Mb while Mac use 600 Mb?

I am just running test_memory_leak without any other things.

And it seems that I can still find memory leak:

<img width="1104" alt="image" src="https://user-images.githubusercontent.com/22206995/103339007-33016000-4abb-11eb-8a85-ed56df44373d.png">

**Comment by lqy0057** [comment]
1. Windows has its own graphics card, so does my ubuntu. Another part of data is on GPU memory
2. ?????

**Comment by pengzhenghao** [comment]
A formal comparison on the impact of multi-threading in Mac is given:

<img width="1111" alt="image" src="https://user-images.githubusercontent.com/22206995/103343200-80cf9580-4ac6-11eb-8757-6d712758cb36.png">


I don't think it is a propitiate time to upgrade Panda3D.

The next figure is the same as above one but more zoomed in.

<img width="833" alt="image" src="https://user-images.githubusercontent.com/22206995/103343255-a0ff5480-4ac6-11eb-8a97-ced26b36c8ad.png">

**Comment by pengzhenghao** [comment]
@lqy0057 Could you please repeat the with/without-multithreading-experiment in linux? Just using the standard way (mprof) as we said in the file.

**Comment by rdb** [comment]
Are you suggesting this issue is *worse* in 1.10.8 than in 1.10.5, then?

**Comment by lqy0057** [comment]
> Are you suggesting this issue is _worse_ in 1.10.8 than in 1.10.5, then?

It is better and works well on both linux and windows machine. And memory usage is stable on these two platforms in both *pstats* and memory_profiler. But it seems that a little memory still leaks on MacOs, no matter whether we turn on multi-thread rendering or not

**Comment by pengzhenghao** [comment]
Hi @rdb ! The following figure is my test on two version of panda3d in two setting.

<img width="1118" alt="image" src="https://user-images.githubusercontent.com/22206995/103344560-e8d3ab00-4ac9-11eb-8a9c-8dd977cbb734.png">

The following are the zoomed in curves.

<img width="841" alt="image" src="https://user-images.githubusercontent.com/22206995/103344688-423bda00-4aca-11eb-8197-d610888a0f04.png">

It seems that the issue is much relieved in the latest panda3d! 
Panda3D 1.10.8 with multi-threading get similar result than Panda3D 1.10.5 without multi-threading.

It seems that the memory increment is quite normal, at least it's not so serious. But it might also indicate some other source of leakage, just for your information~~ @rdb 


@lqy0057 Let's merge the PR.

**Comment by lqy0057** [comment]
### Add ubuntu 16.04 with panda3d-1.10.8 results:
![ubuntu_m_p](https://user-images.githubusercontent.com/24489294/103345044-49afb300-4acb-11eb-8bbd-4530c953bf38.png) 
**Blue**: multi-thread **on**
**black**: multi-thread **off**

**Comment by rdb** [comment]
> It seems that the memory increment is quite normal, at least it's not so serious. But it might also indicate some other source of leakage, just for your information~~ @rdb

Thanks.  It might be useful to open the "System memory" chart in PStats and see which type in Panda is using up more memory.  You can click the categories to zoom into them.

**Comment by pengzhenghao** [comment]
> > It seems that the memory increment is quite normal, at least it's not so serious. But it might also indicate some other source of leakage, just for your information~~ @rdb
> 
> Thanks. It might be useful to open the "System memory" chart in PStats and see which type in Panda is using up more memory. You can click the categories to zoom into them.

I can't launch the pstats. That's quite weird. It shows:

<img width="378" alt="image" src="https://user-images.githubusercontent.com/22206995/103346539-3dc5f000-4acf-11eb-83db-e8c7bb23da5d.png">

**Comment by rdb** [comment]
Oh, we don't build PStats on macOS because it uses the GTK library, sorry about that.

You can run it over the network on another computer and set `pstats-host <ip address>` in Config.prc, but if it's too much trouble, never mind.
