### ISSUE TITLE
Real time simulation

### ISSUE THREAD

**Issue by lqy0057** [decisionforce/pgdrive#211]
We will add an option to do a real time simulation

**Comment by pengzhenghao** [comment]
Remove the insert frame option since it is useless to user

**Comment by lqy0057** [comment]
In game industry, the real time simulation is did by using the time interval between last frame and current frame as the parameter of doPhysics(). But in PGDrive the minimal physics world step size is fixed to 0.02, which means we should lock the render fps to 50 hz to achieve a real time simulation. So I cannot adjust the render frame rate without changing the physics world step size...
