### ISSUE TITLE
Problem on opening the simulator

### ISSUE THREAD

**Issue by JasonKung98** [decisionforce/pgdrive#216]
Hi, this is my first time of using your simulator, hopefully you may bear with me a little, thanks in advance.

I just follow the instructions as stated in your documentation, but I am stucked here as shown. May I know what are the possible errors that I done?
![image](https://user-images.githubusercontent.com/56013789/103459934-65c28700-4d4d-11eb-8689-83cc2ef435aa.png)

**Comment by lqy0057** [comment]
Hi, JasonKung. Did you install PGDrive via pip? If so, please install it by 
```
git clone https://github.com/decisionforce/pgdrive.git
cd pgdrive
pip install -e .
```
Our pip official wheel is not the latest, so this bug happened.

**Comment by JasonKung98** [comment]
Hi developer lqy0057! Thanks for reaching out my problem here. The above code i had executed, but just when I execute this command, python -m pgdrive.examples.profile_pgdrive , i got the errors shown earlier. Is there other packages that I have to install as well? Thanks!

**Comment by pengzhenghao** [comment]
> Hi developer lqy0057! Thanks for reaching out my problem here. The above code i had executed, but just when I execute this command, python -m pgdrive.examples.profile_pgdrive , i got the errors shown earlier. Is there other packages that I have to install as well? Thanks!

Could you please try `pip uninstall pgdrive` before installing the latest wheel? 

By the way, seems this bug is only related to the destroy. May I ask if other functionality of PGDrive works well in your computer? Thanks!

**Comment by JasonKung98** [comment]
Hello developer pengzhenghao! Thanks for reaching here, what is meant by "related to the destroy"? I tried the other functions as well but still throw me the same errors.

**Comment by JasonKung98** [comment]
Update: I do notice this:
"The above script is supposed to be runnable in all places. Note that please do not run the above command in the folder that has a sub-folder called ./pgdrive."

However, I manually open the directory and found out the python files such as enjoy_expert, enjoy_manual, profile_pgdrive are all in the subfolder pgdrive. May I know what should I do for now? Thanks in advance

**Comment by lqy0057** [comment]
> Hello developer pengzhenghao! Thanks for reaching here, what is meant by "related to the destroy"? I tried the other functions as well but still throw me the same errors.

Don't worry my friend. These errors were thrown when calling env.close() to terminate or **destroy** the simulation, so you can ignore them.  ```python -m pgdrive.examples.enjoy_manual``` and ```python -m pgdrive.examples.enjoy_expert```  still work.
And these errors can be solved by installing pgdrive in a new *conda* environment and installing PGDrive-main by ```git clone```. We will update the pip wheel soon.

**Comment by lqy0057** [comment]
> Update: I do notice this:
> "The above script is supposed to be runnable in all places. Note that please do not run the above command in the folder that has a sub-folder called ./pgdrive."
> 
> However, I manually open the directory and found out the python files such as enjoy_expert, enjoy_manual, profile_pgdrive are all in the subfolder pgdrive. May I know what should I do for now? Thanks in advance

```python -m``` means running python script as module, so you can run this command everywhere except a working directory that has a sub-folder called ./pgdrive

**Comment by JasonKung98** [comment]
Hi lqy0057! Thanks for the detailed explanation here. I saw the files are inside this folder, by right I think I should not run from here right? As per the instructions given from you. I ran the earlier commands in the pgdrive main folder. Thanks!
![image](https://user-images.githubusercontent.com/56013789/103460926-665f1b80-4d55-11eb-81ad-c20363c3ded3.png)

**Comment by JasonKung98** [comment]
Hi, thanks again for trying to solve my problem here. May I know is there is any difference of using pathlib and "os.path.dirname(__file__)"? I am still new to Python so I wish to learn a bit more of the writing. Thank you so much!

**Comment by lqy0057** [comment]
> Hi, thanks again for trying to solve my problem here. May I know is there is any difference of using pathlib and "os.path.dirname(**file**)"? How I should replace it in the Python code? I am still new to Python so I wish to learn a bit more of the writing. Thank you so much!

Thanks for opening this issue, We find your OS is Windows, and  Win32 platform is case-insensitive, which may raise error  when loading assets of PGDrive. It can be solved by using [these methods](https://stackoverflow.com/questions/3692261/in-python-how-can-i-get-the-correctly-cased-path-for-a-file/30374360).

**Comment by pengzhenghao** [comment]
Hi @JasonKung98 We have already update PGDrive, could you please try to install the latest version via:

`pip install -U pgdrive`

and see if everything work well?

Thanks!

**Comment by JasonKung98** [comment]
Hi! @lqy0057  and @pengzhenghao ! Thanks for spending your time again looking for any solutions for my problem. Thanks for the given suggestions as well, will try it out recently to see if it works. Please do remain this post opened until resolved, I would be glad if I may receive further assistance from you 👍

**Comment by JasonKung98** [comment]
Update: Hi, after pip install -U pgdrive and follow the instructions stated :
git clone https://github.com/decisionforce/pgdrive.git
cd pgdrive
pip install -e .
python -m pgdrive.examples.profile_pgdrive

i still couldn't make it run, is it really the issue of "Use pathlib to replace all "os.path.dirname(__file__)" here? I am not familiar of dealing with pathlib in my code, thank you so much !

**Comment by pengzhenghao** [comment]
Close this issue temporarily. Feel free to reopen if necessary!
