### ISSUE TITLE
Use pathlib to replace all "os.path.dirname(__file__)"

### ISSUE THREAD

**Issue by pengzhenghao** [decisionforce/pgdrive#218]
pathlib seems like a good library that can fix windows' path issue. 

Link:  #216

**Comment by lqy0057** [comment]
![image](https://user-images.githubusercontent.com/24489294/103507058-34ef6880-4e99-11eb-8674-31e5668ac584.png)
solved this problem on Win32 by using pathlib
@pengzhenghao please test on MacOS, branch: use-pathlib

**Comment by pengzhenghao** [comment]
Are you sure this will fix the issue when installing the wheel and run `enjoy_xx.py`?

Please verify this via: 

`pip install git+https://github.com/decisionforce/pgdrive.git`

or

`pip install git+https://github.com/decisionforce/pgdrive.git@BRANCH_NAME`

This is equivalent to install from pip package.

**Comment by lqy0057** [comment]
![image](https://user-images.githubusercontent.com/24489294/103605082-d637f680-4f4d-11eb-92dc-207bad4a0c3c.png)
![image](https://user-images.githubusercontent.com/24489294/103605143-17300b00-4f4e-11eb-85e5-6864d2ad7fa0.png)

It is weird that ```pip install git+https://github.com/decisionforce/pgdrive.git'`` doesn't clone the assets on windows10.

But I succeed to run it, after copy the asset folder to the ```my_env/site-packages/pgdrive```
![image](https://user-images.githubusercontent.com/24489294/103605316-8e659f00-4f4e-11eb-8461-2b5d15d6db6a.png)

**Comment by lqy0057** [comment]
Linux has not such a problem
![linux](https://user-images.githubusercontent.com/24489294/103605626-5a3eae00-4f4f-11eb-80c8-f5d899f0675c.png)
All assets are downloaded successfully

**Comment by pengzhenghao** [comment]
Please fix windows-asset problems (Have you check the actual folder? Maybe the asset just has wrong path.)

**Comment by lqy0057** [comment]
> Please fix windows-asset problems (Have you check the actual folder? Maybe the asset just has wrong path.)

I have searched the whole folder of the anaconda, and can not find the assets of pgdrive.
Besides, the model of the expert agent also disappeared. These binary files may be filtered by something when installing.
I don't think it is a problem if we release a new  pgdrive.whl on Pypi. Since the wheel file installed by ```pip install pgdrive``` contains all things.

**Comment by pengzhenghao** [comment]
Good! Let’s submit a 0.1.2.rc0 version first!


Best regards!

Peng Zhenghao (彭正皓)
