### ISSUE TITLE
Model overlap

### ISSUE THREAD

**Issue by pengzhenghao** [decisionforce/pgdrive#223]
<img width="1312" alt="image" src="https://user-images.githubusercontent.com/22206995/103532499-50bd3380-4ec6-11eb-8a53-6553c91bf0aa.png">

This happen when I am using `real-simulation` branch expert_mannual.py

**Comment by lqy0057** [comment]
This will be fixed soon. All traffic vehicles' visualization models and physics models are in different sizes.

**Comment by lqy0057** [comment]
Model size has been adjusted, and a small roundabout bug is fixed in this pr.
It seems that the expert behaves better after fixing this bug.

**Comment by lqy0057** [comment]
![Uploading image.png…]()
success rate: 28/30 = 0.93, merge
