### ISSUE TITLE
Improve the github CI workflow to give clearer information

### ISSUE THREAD

**Issue by pengzhenghao** [decisionforce/pgdrive#227]
Now there is only one build. We can't see the which stage of the building fails, such as code styling or blackbox tests. This is uninformative.

Can we split the workflow to multiple builds that allows clearer message in github email and also PR webpage?

**Comment by pengzhenghao** [comment]
<img width="885" alt="image" src="https://user-images.githubusercontent.com/22206995/103558921-5596dd00-4ef0-11eb-8156-252558b884fa.png">

Just like this.

**Comment by lqy0057** [comment]
Can we create work flow for each job?

**Comment by pengzhenghao** [comment]
Closed by #228
