### ISSUE TITLE
Static error in steering when using joystick

### ISSUE THREAD

**Issue by pengzhenghao** [decisionforce/pgdrive#231]
<img width="1312" alt="image" src="https://user-images.githubusercontent.com/22206995/103867670-b85fc280-5102-11eb-9f6e-d5b5cd1da5cb.png">

As you can see in the right corner. I don't make movement in the joystick but it still detect a static steering value.

**Comment by lqy0057** [comment]
Is the raw data incorrect, or maybe a render error?

**Comment by pengzhenghao** [comment]
It’s not a render errror. the vehicle is indeed making small turning even if I don’t make command using joystick

**Comment by pengzhenghao** [comment]
<img width="602" alt="image" src="https://user-images.githubusercontent.com/22206995/103901550-3ee0c800-5134-11eb-9cdd-610321a76299.png">


* [ ] Check whether the output from joystick is in [-1, 1].
* [ ] Maybe we can add a dead zone (like considering the input is 0 if the input is in [-0.01, 0.01].)

**Comment by pengzhenghao** [comment]
I don't have joystick all the time (the one is friend's and used in his home). So I can't help to solve this issue.
