### ISSUE TITLE
Support for Multi agent training

### ISSUE THREAD

**Issue by AizazSharif** [decisionforce/pgdrive#247]
Hi,

I wanted to ask if PGDrive supports multi-agent vehicle training. If not, can we use the pre-trained model in the ego vehicle while training another vehicle in parallel using RL?

Any information will be helpful.

Thanks.

**Comment by lqy0057** [comment]
Yes, you can fork this project and do a little modification to build your own multi-agent env (changing the ```ego_vehicle``` variable to a list ). Unlimited BaseVehicle() equiped with different sensors can be created in PGDrive. Although it is in our roadmap, an official multi-agent environment will be released after several months.

**Comment by AizazSharif** [comment]
Thanks for the response.

I also wanted to ask how to add an existing gym or baseline RL algorithm in the code for training. The existing code so far supports PPO and SAC only for now using Rlib.

Regards.

**Comment by pengzhenghao** [comment]
> Thanks for the response.
> 
> I also wanted to ask how to add an existing gym or baseline RL algorithm in the code for training. The existing code so far supports PPO and SAC only for now using Rlib.
> 
> Regards.

Hi @AizazSharif !

PGDrive, at least in this repo, only provides the Gym-compatible environment for RL training. You can use arbitrary RL libraries to conduct training. But you have to follow the library-specified procedure to register and setup the Gym environment instance.

For example, you can create an environment instance via:

```python
import pgdrive
env = pgdrive.PGDriveEnv()
trainer.train(env=env)
```

or by calling the `gym.make` to create the environment instance:

```python
import pgdrive
import gym
env = gym.make("PGDrive-v0")
trainer.train(env=env)
```

How to create the environment and how to make it compatible with your RL libraries is subject to the specified workflow of your library. So we can't provide details help here. Thanks!

**Comment by AizazSharif** [comment]
Thanks for the help @pengzhenghao.
