### ISSUE TITLE
How can an agent achieve -6000 reward in saver-existing environment?

### ISSUE THREAD

**Issue by pengzhenghao** [decisionforce/pgdrive#253]
<img width="1928" alt="image" src="https://user-images.githubusercontent.com/22206995/108652614-87dfb680-74ff-11eb-9b2a-ec2141c4d657.png">

This is an issue left for recording progress of me @pengzhenghao and @lqy0057 .

**Comment by lqy0057** [comment]
When Ego vehicle go out of road and expert fails to recover it, Ego vehicle will stay out of road for a long time, which causes the out of road penalty is  added to step reward for a number of times.

**Comment by lqy0057** [comment]
Fixed
