### ISSUE TITLE
Some textures missing during gameplay

### ISSUE THREAD

**Issue by Edwardhk** [decisionforce/pgdrive#261]
### Errors messages:
Encountered this issue on latest master branch
![image](https://user-images.githubusercontent.com/18554116/110295107-af6c6e00-802b-11eb-9f15-20b3fa601009.png)
```
:gobj(error): Texture::read() - couldn't read: ./wood.png
:gobj(error): Unable to find texture "./wood.png" on model-path /tmp:/home/work/dev/MASTER/pgdrive/pgdrive/assets/models:/tmp:/home/work/dev/MASTER/pgdrive/pgdrive/assets/models/ferra:/home/work/dev/MASTER/pgdrive:/home/work/anaconda3/envs/rl_dev/lib/python3.7/site-packages/panda3d/etc/..:/home/work/anaconda3/envs/rl_dev/lib/python3.7/site-packages/panda3d/etc/../models
```

Some textures seem to be missing during rendering (the green box), the game-play itself is not being affected.
![image](https://user-images.githubusercontent.com/18554116/110295228-d4f97780-802b-11eb-99b0-c6c373a1af63.png)

### Command used:
```
python -m pgdrive.examples.enjoy_expert
```

**Comment by lqy0057** [comment]
I encountered this issue occasionally. But I can not reproduce it this time... Changing the navigation point model, "box.egg", to "box.bam" in ```routing_localization.py``` maybe useful.

**Comment by pengzhenghao** [comment]
Wait, so this is really an issue? I mean does there really a "wood.pnd" in some place an it is not shown?

**Comment by lqy0057** [comment]
Use box.bam instead of box.egg can solve this problem when developing PGDrive. I recommend removing the box.egg in our repo

**Comment by Edwardhk** [comment]
The attribute has been replaced in [release/0.1.4](https://github.com/decisionforce/pgdrive/pull/269) and merged into master.

**Comment by lqy0057** [comment]
ohhhh, that is weird... Some errors must exist in .egg/.bam model file.

**Comment by pengzhenghao** [comment]
@lqy0057 Is this issue still there?
