### ISSUE TITLE
Reconstruct reward function

### ISSUE THREAD

**Issue by pengzhenghao** [decisionforce/pgdrive#266]
We have too complex reward function now, and is possibly the reason why the behavior is too conservative! For example, the penalty on the longitude should be removed!

**Comment by lqy0057** [comment]
I have removed it in MARL-env branch

**Comment by pengzhenghao** [comment]
How can you just remove it without experiments......................

We are not Alchemists!!!

**Comment by lqy0057** [comment]
I did experiments.  I am sure that overtaking will be learned after removing it

**Comment by pengzhenghao** [comment]
Well, just put it in future PGDrive 2.0 branch

MARL-env is only providing infrastructure

**Comment by lqy0057** [comment]
OK

**Comment by pengzhenghao** [comment]
The original purpose of lateral penalty is to relieve jerky behavior. So would removing such reward re-introduce such behavior?

**Comment by lqy0057** [comment]
Maybe we should train a new expert without lateral factor to verify it. But it definitely prevents the agent from learning to overtake.

**Comment by pengzhenghao** [comment]
This issue is already addressed for a long time! Great!
