### ISSUE TITLE
Allow kicking off expert for one and manual control for another in MARL env

### ISSUE THREAD

**Issue by pengzhenghao** [decisionforce/pgdrive#277]
<img width="897" alt="image" src="https://user-images.githubusercontent.com/22206995/111164435-0a2c3980-85d9-11eb-9618-0dcbb95e9d26.png">

I wish to press T to kick off an expert running agent 0 and manually control agent 1, but this bug happen!

(By the way, key T is not shown in helper message, but that's OK, please don't add it to helper message until formally release PGDrive v0.2)

**Comment by lqy0057** [comment]
Solved in #272
