### ISSUE TITLE
Reward scheme for PGDrive v0.2.0

### ISSUE THREAD

**Issue by pengzhenghao** [decisionforce/pgdrive#283]
Note: This is not a normal issue and please don't close this. We use this issue to record the useful information on the reward scheme design.

Best choices:

- steering_penalty = 0
- out_of_road_penalty = 5
- success_reward = 10

Reason: 

![](https://firebasestorage.googleapis.com/v0/b/firescript-577a2.appspot.com/o/imgs%2Fapp%2Fpengzh%2Fc8Xyryv8xz.png?alt=media&token=e0223dc2-fdd9-41ca-8353-06f48141daab)

Best choices:

- use lateral = True
- crash_vehicle_penalty = 5
- speed_reward = 0.1

Reason:

![](https://firebasestorage.googleapis.com/v0/b/firescript-577a2.appspot.com/o/imgs%2Fapp%2Fpengzh%2FQ0bfOU1Lcm.png?alt=media&token=258437fe-9c13-469c-8eb3-c9a7b4acaba9)

Final decision:

![](https://firebasestorage.googleapis.com/v0/b/firescript-577a2.appspot.com/o/imgs%2Fapp%2Fpengzh%2FHw2g3aQr74.png?alt=media&token=fee0963f-cc33-4693-8053-c5786307e232)

Using lateral reward multiplier will lead to better success rate, but that constrains the velocity as well as the behavior diversity. So we tend to close this thing, also in order to simplify the reward.

We choose to use:

1. `use_lateral = False`
2. `speed_reward = 0.5`

And this is the final decision.

One more thing we want to say is that current practice will damage PPO seriously:

![image](https://user-images.githubusercontent.com/22206995/112097595-43693880-8bdb-11eb-99a7-8322628dfb46.png)

-----

**Note: The following content is proved to be wrong and the result is not trustworthy. Please use the conclusion above.**

<details>
  <summary>Click to expand!</summary>
**Out of Road penalty and Steering Reward**

(Trained with PPO, 100 envs.)

![image](https://user-images.githubusercontent.com/22206995/111186511-0b1b9600-85ee-11eb-9f31-b6d9790fc0a8.png)

![image](https://user-images.githubusercontent.com/22206995/111186714-3e5e2500-85ee-11eb-89a6-6b050e409d49.png)

![image](https://user-images.githubusercontent.com/22206995/111186841-6057a780-85ee-11eb-8fa4-49d1fd837f07.png)

Conclusion:

1. Setting both of them to 0 is a good idea!
2. There two factors are highly coupled!

**Two sparse terminal rewards: Crash vehicle penalty and success reward**

When out of road penalty and steering reward is set to 0, we vary the following components to see their impact:

1. `crash_vehicle_penalty`
2. `success_reward`

These are two "sparse" reward which is given at the very end of the episode.

Here is the training / test success rate:

![image](https://user-images.githubusercontent.com/22206995/111711630-1fc68b00-8887-11eb-849d-9f13e9d13497.png)

Conclusion:

1. Use `crash_vehicle_penalty = success_reward = out_of_road_penalty = steering_penalty = 0` or
2. Use `crash_vehicle_penalty = 5; success_reward = 20; out_of_road_penalty = steering_penalty = 0`

**Varying the `general_penalty` as well as the `speed_reward`**

This experiments is conducted with Soft Actor-Critic, a must-tuned algorithm. We set the stop criterion to 0.96 success rate as well as 1M timesteps.

1. `reward v1` means `crash_vehicle_penalty = success_reward = 0`
2. `reward v2` means `crash_vehicle_penalty = 5; success_reward = 20`

![image](https://user-images.githubusercontent.com/22206995/111873912-b1401500-89cd-11eb-93d5-d92e57eabe58.png)

Detail curves:

![image](https://user-images.githubusercontent.com/22206995/111874159-d41ef900-89ce-11eb-9357-1e654d78f7ab.png)

The best experiments setting for SAC is:

1. `reward v1` where `crash_vehicle_penalty = success_reward = 0`
2. `general_penalty = 0` 
3. `speed_reward = 0.5`

But, however, PPO yield best in `reward v2`. So I wish to conduct one more experiment to get the final decision!

![image](https://user-images.githubusercontent.com/22206995/111898749-e0ed2c80-8a62-11eb-933d-e4b61bab207e.png)
</details>

**Comment by lqy0057** [comment]
Is this issue the same as #266 ?

**Comment by pengzhenghao** [comment]
Yes, but just leave it here.
