### ISSUE TITLE
Observation scheme for PGDrive v0.2.0

### ISSUE THREAD

**Issue by lqy0057** [decisionforce/pgdrive#297]
- New observation when lane num change on the navigation.
- Add new blocks to change the lane num/width

**Comment by pengzhenghao** [comment]
# What is the good observation?

The prime goal of observation engineering is to determine the format of observation that:

1. Stablize training
2. Informative but not too easy
3. Fast and efficient

## What is the good format of lidar?

(PPO, environment_num=100, 3 seeds)

![image](https://user-images.githubusercontent.com/22206995/111867038-6eba1080-89ac-11eb-871d-2fd2a4839c3f.png)

The best:

- distance = 50, num lasers = 120, num others = 0
- distance = 100, num lasers = 120, num others = 0
- distance = 200, num lasers = 120, num others = 4
- distance = 200, num lasers = 360, num others = 0

The details of the best:

![label = 120 laser, 100 distance, 0 others](https://user-images.githubusercontent.com/22206995/111867318-23a0fd00-89ae-11eb-8345-50208aacc11c.png)

For the sake of simplicity and minimality, we choose:

**distance = 50, num lasers = 120, num others = 0**

**Comment by pengzhenghao** [comment]
# Discussion on the state design

Current state include two parts:

```
Ego states: [
            0: Distance to left yellow Continuous line,
            1: Distance to right Side Walk,
            2: Difference of heading between ego vehicle and current lane,
            3: Current speed,
            4: Current steering,
            5: Throttle/brake of last frame,
            6: Steering of last frame,
            7: Yaw Rate,
            8: Lateral Position on current lane.
            ], dim = 9
Navi info: [
            0: Projection of distance between ego vehicle and checkpoint on ego vehicle's heading direction,
            1: Projection of distance between ego vehicle and checkpoint on ego vehicle's side direction,
            2: Radius of the lane whose end node is the checkpoint (0 if this lane is straight),
            3: Clockwise (1) or anticlockwise (0) (0 if lane is straight),
            4: Angle of the lane (0 if lane is straight)
           ] * 2, dim = 10
```


## Target vehicle's state
For the ego states, my first instinct is to remove 0, 1, 2, 8, replace them with a layer of lidar that shot on the boundary of the road network (not the navigation lanes!)

My ideal design would be:

```
ego state = [
    lidar for the boundary of the road network of current frame T; 
    current speed;
    current yaw rate;
    current steering;
    current acceleration;
    last speed;
    last yaw rate;
    last steering;
    last acceleration;
]
```

Totally 120 + 4 + 4 = 128 dims.

**Frame stacking might be useful! We can also return the frame at T-5.**


## Navigation 

My ideal design is:

```
Navi info: [
    0: relative distance to next checkpoint in heading direction,
    1: relative distance to next checkpoint in side direction,
    2: same as 0 but for next next checkpoint,
    3: same as 1 but for next next checkpoint.
]
```

Totally 4 dims.


## Traffic

Originally, we use 240 lines lidar. But the above experiments show that using 120 lines is a better idea and we should remove the neighbour information.

Consider that we should also infering other's vehicle's information, a good idea is to introduce stacking. **Frame stacking might be useful! We can also return the frame at T-5.**

## Conclusion

If we are using stacking, then the total amount of data should be: `120 * 2 + 120 * 2 + 12 = 492`.

If not, then `120 + 120 + 12 = 252`.

Just take try!
