### ISSUE TITLE
Can we remove the compression option and let system auto decides whether to compress texture?

### ISSUE THREAD

**Issue by pengzhenghao** [decisionforce/pgdrive#298]
Previously, we use the `loadPrcFileData("", "compressed-textures 1")` to make sure PGDrive won't break down the low-performance computer.

However, it do really cost much more time in displaying the window (10x slower).

<img width="546" alt="image" src="https://user-images.githubusercontent.com/22206995/111590770-81441680-8801-11eb-8fbb-38a3fdcaba64.png">

Do we have any solution to let PGDrive automatically decides whether to use compression or not?

CC @rdb for your potential idea on this issue. Thanks!

@lqy0057 May be we can generate intermediate file in advance and let PGDrive loads the compressed asset when starting.

**Comment by rdb** [comment]
The best way to deal with this is to precompress the textures and then save them in the DDS or TXO format.

You can alternatively tell Panda to cache the compressed textures using `model-cache-compressed-textures 1` in Config.prc.  Then it should only be slow on first load.

**Comment by lqy0057** [comment]
Hi, rdb. Thanks for your help! We will try it soon!
