### ISSUE TITLE
Optimize reborn traffic mode

### ISSUE THREAD

**Issue by pengzhenghao** [decisionforce/pgdrive#310]
Related: #243 

Current reborn mode is not so perfect, but I wish to use it as the default traffic mode in PGDrive V2.

Almost all vehicles are concentrated near the born place of ego vehicle.

@lqy0057

**Comment by lqy0057** [comment]
They will be reborn at available sockets

**Comment by pengzhenghao** [comment]
So this issue is resolved now?
