### ISSUE TITLE
Randomize vehicles appearance with different color

### ISSUE THREAD

**Issue by pengzhenghao** [decisionforce/pgdrive#439]
Hi @Edwardhk ! Prof. provides an idea that we should make the target vehicles colorful instead of only using red skin!

Previously, @zqh0253 has tried to overwrite the model's texture with pure colors, could you please provides a tutorial on how to do this? We will formalize that idea and create a formal pipeline for color randomization!

@Edwardhk could you please also add this into your to do list? That's an important feature for visualization! Here I draw some items that might need to be used:

1. find a way to color a single vehicle, create a function for this. If the color of vehicle can be changed run-time that would be great! (run-time means, since we are in MARL env, change the color when re-spawning an existed vehicle to a new location).
2. call this function when initializing and re-spawning vehicles to new spawn points
3. provide a config entry to enable / disable this feature
4. choose a color platte that are colorful yet beautiful

@lqy any other suggestion? 

Thanks!

**Comment by zqh0253** [comment]
If you want to overwrite a model's texture and apply customized color, you could write a **shader** and apply that shader to the rendered object. 
The DepthCAM in PGDrive is also implemented in this way. You could have a look at its [vertice shader file](https://github.com/decisionforce/pgdrive/blob/main/pgdrive/assets/shaders/depth_cam.vert.glsl) and [fragment shader file](https://github.com/decisionforce/pgdrive/blob/main/pgdrive/assets/shaders/depth_cam.frag.glsl).

**Comment by pengzhenghao** [comment]
Please feel free to raise question here! @Edwardhk
