### ISSUE TITLE
Refactor the coordination system

### ISSUE THREAD

**Issue by pengzhenghao** [decisionforce/pgdrive#483]
## Current issues

* Base Vehicle or Traffic Vechile requires  (- np.pi / 2) when setting the heading.

## Roadmap

...

**Comment by lqy0057** [comment]
BulletVehicle's heading is in the +y direction of the object's coordinate, and thus the length is set in this direction by adding shape(width, length, height), while the getH() is calculated by using the object's +x direction. 
![image](https://user-images.githubusercontent.com/24489294/127744013-cc63aea7-7218-480a-bc38-2fadf72d4b5b.png)

**Comment by pengzhenghao** [comment]
Solved right now! We using +y to represent the direction of the vehicle's head and use +x to represent the right hand side of the vehicle!
