### ISSUE TITLE
Garbage collect costs too much time?

### ISSUE THREAD

**Issue by pengzhenghao** [decisionforce/pgdrive#496]
![0814_2325](https://user-images.githubusercontent.com/22206995/129451195-4d4555b1-be06-4451-b84d-438c5b9d2ba5.png)

So surprising! It costs 50% time?????????

**Comment by lqy0057** [comment]
The time for garbage collection is mostly used by python built-in garbage collection instead of Panda3D's garbage collection. It is easy to solve by turning the auto-garbage collection off in python3, if our code is well written to ensure memory-safe.

**Comment by pengzhenghao** [comment]
<img width="530" alt="image" src="https://user-images.githubusercontent.com/22206995/129473869-3bdbf121-9364-4b54-a0ba-b8142960d557.png">

We can change every `self.object` by `self.object_name`.
