### ISSUE TITLE
Efficiency decreases drastically in long run

### ISSUE THREAD

**Issue by pengzhenghao** [decisionforce/pgdrive#504]
![pgdrive84](https://user-images.githubusercontent.com/22206995/129508135-74bee976-49a5-4f60-b006-80c63f51336a.png)

Here is the reason. The garbage collection in panda3d!

**Comment by lqy0057** [comment]
![image](https://user-images.githubusercontent.com/24489294/129514513-f8f7522b-5670-41af-a20c-8495b686c60b.png)
