### ISSUE TITLE
Validate the state save & restore is working

### ISSUE THREAD

**Issue by pengzhenghao** [decisionforce/pgdrive#51]
The primal goal:

Use the trajectory from lidar-specified environment, to generate a new RGB-image observation trajectory.

This is the preliminary functionality, before we wish to use lidar-based agent to generate image-based trajectory for imitation learning.

To Do List:

* [x] Can single vehicle state be perfectly restored?
* [x] Can opponent vehicle state be perfectly restored?
* [x] Can the image observation be perfectly restored?

**Comment by lqy0057** [comment]
dump episode is ready now!
