### ISSUE TITLE
how to close the status bar

### ISSUE THREAD

**Issue by hickey23** [decisionforce/pgdrive#542]
Hello, for some reason, I want to try to close the status bar of pgdrive, such as display speed, FPS, etc., but I can't find how to close it. Could  you tell me how to close this status bar? Thank you very much!!
[1](https://user-images.githubusercontent.com/50687983/179669255-805e443d-3675-4737-92c4-dc07ce94eefa.png)

**Comment by hickey23** [comment]
![Uploading 1.png…]()

**Comment by hickey23** [comment]
![1](https://user-images.githubusercontent.com/50687983/179669594-5c8f743a-764c-499e-8a4e-2267c5989a20.png)

**Comment by pengzhenghao** [comment]
Hi @hickey23 , thanks for reaching out.

We actually do this before, by forcefully commenting out the relevant code in this file:

https://github.com/decisionforce/pgdrive/blob/b2671743c6b45cf7659e304a1cf06a7d064303fd/pgdrive/engine/interface.py#L22

You can go through this file and remove things like left/middle/right panels and banners. Remember also remove relevant code that updating them.


FPS can be removed by config: `Env({"show_fps": False})` as shown: https://github.com/decisionforce/pgdrive/blob/2e7e7d2303b81d8877ed07c8eb77d52bcfd30d8d/pgdrive/envs/base_env.py#L71


As a reminder, PGDrive is no longer maintained. Please switch to MetaDrive instead: https://github.com/metadriverse/metadrive



One last tips: You can call `env.engine.win.getScreenshot(img)` to save current visualization images as shown here:

https://github.com/decisionforce/pgdrive/blob/ad1d3ec7fc723bc174280c988a9eab99cac14fd7/pgdrive/tests/vis_funtionality/vis_installation.py#L24

**Comment by hickey23** [comment]
Thanks for your reply!!!
I am gonna try it ,thanks again sincerely!!!
